### ISSUE TITLE
实时预览模式下显示正常，阅读模式下显示不正常。

### ISSUE THREAD

**Issue by darknesscho** [no33jou/obsidian-modevol-plugin#1]
阅读模式下变成了这个样子
![image.png](https://tu.darkc.fun:5180/i/2023/03/16/unk2oo-0.webp)

**Comment by darknesscho** [comment]
主题是Minimal，不知道跟非官方主题是否有关。

**Comment by no33jou** [comment]
这是个bug ，和主题没关系，下个版本修复

**Comment by darknesscho** [comment]
收到！

**Comment by darknesscho** [comment]
建议阅读模式和实时预览模式保持一样的显示。现在这样仅显示一个小图标并不直观，不能马上反应过来是什么类型的信息。
<img width="143" alt="image" src="https://user-images.githubusercontent.com/58537971/225599308-5568a5a2-4e64-475d-8e4c-98e99988f1aa.png">
还是显示成这样的文字好点。

**Comment by no33jou** [comment]
我还想把编辑模式改成阅读模式一样，因为我们需要更简单的符号或者颜色去识别出一段文字的类型，而不是中文，

你是modevol 社群的吧？ 进[社群](https://chat.modevol.com/modevol/channels/obsidian)聊，
我很少看github，issues有信息就邮件就铛铛的响以为公司出事了😂

**Comment by darknesscho** [comment]
或者给一个插件设置页面，让用户自己选择吧。不打扰啦，我没有在渐构的社群中。

**Comment by no33jou** [comment]
没问题，我记录下来这个优化点，它在未来某个版本上出现，最近版本都是在做outline的优化。

很高兴，我能有一个非社群的插件使用者，issues随便聊😄
