### ISSUE TITLE
标签#c不起效果，其它的都可以

### ISSUE THREAD

**Issue by qiuchongquan** [no33jou/obsidian-modevol-plugin#3]
![image](https://user-images.githubusercontent.com/128764643/230710746-10f0d3ce-d7f7-42d6-8363-70fb23eaf3f0.png)

**Comment by Ysenxxx** [comment]
#c是你自己要在后面自定义一段文字去用的

**Comment by Ysenxxx** [comment]
比如，#c于博，你换行后显示的就是渲染后的（于博）

**Comment by no33jou** [comment]
格式： #c 问题 浆果的提问
c是自定义类型，‘问题’是标签的类型，分隔符是空格
